### PR TITLE
Add usage message

### PR DESCRIPTION
**Pull request by Bunogi**

### CODE REVIEW

**Comment by f2404** [comment]
Aren't 4 lines too much for such a short message?

**Comment by Bunogi** [comment]
I wanted to avoid including `string.h`, might look a little better if you put the 4 macro calls onto a single line, though.

**Comment by f2404** [comment]
Why not put it like

``` c
    ERROR("Usage: %s [K/M]PID ...\n", argv[0]);
```

**Comment by Bunogi** [comment]
I agree, that is better. Changed it now.

**Comment by nickodell** [comment]
Yep, that works.

Thanks, you two.

**Pull request merged**
