### PR TITLE
Makefile optimization

### PR DESCRIPTION
**Pull request by f2404**

### CODE REVIEW

**Comment by nickodell** [comment]
This was a good suggestion, but I needed to change the else to an endif to make the Makefile work. I appreciate the help, but please please test stuff before submitting a PR.

**Comment by f2404** [comment]
Oops, sorry, my bad indeed. I did test it but missed that when editing.

**Comment by nickodell** [comment]
PS. I just changed the license. Are you OK with your changes being released under the [WTFPL](http://www.wtfpl.net/txt/copying/) license?

**Comment by f2404** [comment]
I think this is a really good one :)

**Pull request merged**
